// Generated file. Regenerated by `flutter pub get`. Do not edit by hand.
#import "GeneratedPluginRegistrant.h"
#import <sqflite_darwin/SqflitePlugin.h>
#import <path_provider_foundation/PathProviderPlugin.h>

@implementation GeneratedPluginRegistrant

+ (void)registerWithRegistry:(NSObject<FlutterPluginRegistry>*)registry {
  [SqflitePlugin registerWithRegistrar:[registry registrarForPlugin:@"SqflitePlugin"]];
  [PathProviderPlugin registerWithRegistrar:[registry registrarForPlugin:@"PathProviderPlugin"]];
}

@end
