// Generated file. Regenerated by `flutter pub get`. Do not edit by hand.

#include "generated_plugin_registrant.h"

void fl_register_plugins(FlPluginRegistry* registry) {
  // sqflite_common_ffi handles its own database access on Linux and does
  // not register a Flutter plugin; no entries are needed here for it.
}
