// Generated file. Regenerated by `flutter pub get`. Do not edit by hand.

#include "generated_plugin_registrant.h"

void RegisterPlugins(flutter::PluginRegistry* registry) {
  // sqflite_common_ffi drives SQLite directly on Windows and does not
  // register a Flutter plugin; no entries are needed here for it.
}
